version: '3.4'

services:
  todo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44365
      - Kestrel__Certificates__Default__PASSWORD=apples
      - Kestrel__Certificates__Default__PATH=/root/.aspnet/https/localhost.pfx
    ports:
      - "49167:80"
      - "44365:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44358
      - Kestrel__Certificates__Default__PASSWORD=apples
      - Kestrel__Certificates__Default__PATH=/root/.aspnet/https/localhost.pfx
    ports:
      - "43924:80"
      - "44358:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
